- Source/Examples/DataGrid/DataGridDemo/DataGridDemo_NET40.csproj
- Source/Examples/DataGrid/DataGridDemo/DataGridDemo_NET45.csproj
- Source/Examples/DataGrid/DataGridDemo/Examples/Window102.xaml
- Source/Examples/DataGrid/DataGridDemo/Examples/Window601.xaml
- Source/Examples/DataGrid/DataGridDemo/Examples/Window601.xaml.cs
- Source/Examples/DataGrid/DataGridDemo/MainWindow.xaml
- Source/PropertyTools.Wpf.Tests/Helpers/TypeHelperTests.cs
- Source/PropertyTools.Wpf.Tests/PropertyTools.Wpf.Tests_NET40.csproj
- Source/PropertyTools.Wpf.Tests/PropertyTools.Wpf.Tests_NET45.csproj
- Source/PropertyTools.Wpf/DataGrid/DataGrid.Content.cs
- Source/PropertyTools.Wpf/DataGrid/DataGrid.Strategy.cs
- Source/PropertyTools.Wpf/DataGrid/Definitions/PropertyDefinition.cs
- Source/PropertyTools.Wpf/Helpers/TypeHelper.cs
Sorry, I Based it on my DataTable support patch, when this is merged, this Pull Req will be cleaner
> Tool tip & Custom header support

- Source/PropertyTools.Wpf/DataGrid/DataGrid.cs
Fix the defect: next cell will not go into edit mode.
> Revert previous change.

- Source/Examples/Controls/ControlDemos/Pages/FilePickerPage.xaml
- Source/Examples/Controls/ControlDemos/Pages/FilePickerPage.xaml.cs
- Source/PropertyTools.Wpf/Controls/FilePicker/FilePicker.cs
- Source/PropertyTools.Wpf/Controls/FilePicker/Generic.xaml
- Source/PropertyTools.Wpf/Controls/FilePicker/IFileDialogService.cs
- Added property to FilePicker to allow for multiselect on the file open dialog.
- Updated other relevant portions (IFileDialogService interface, examples, FilePath property) accordingly.
> Add Multiselect to FilePicker

- Source/PropertyTools.Wpf/PropertyGrid/PropertyGrid.cs
Better fix for issue #39.
Having a little trouble with SVN and branch naming. Had to create another branch for it to work.
> Fix for issue #39

- Source/PropertyTools.Wpf/PropertyGrid/Generic.xaml
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGrid.cs
> Issue #59: PropertyGrid: Can't get current active TabId in property view. 

- Source/PropertyTools.Wpf/DataGrid/ControlFactory/DataGridControlFactory.cs
Should set SelectedValuePath for combobox.
> SelectedValuePath is not set when combobox is activated in datagrid.

- Source/Examples/Controls/ControlDemos/ControlDemos_NET45.csproj
- Source/Examples/Controls/ControlDemos/Examples.xml
- Source/Examples/Controls/ControlDemos/MainWindow.xaml
- Source/Examples/Controls/ControlDemos/Pages/EditableTextBlockAndPropertyGridPage.xaml
- Source/Examples/Controls/ControlDemos/Pages/EditableTextBlockAndPropertyGridPage.xaml.cs
- Source/PropertyTools.Wpf/Controls/EditableTextBlock.cs
> Editabletextblock propertygrid example

- Source/Examples/DataGrid/DataGridDemo/Examples/ThreadExample.xaml.cs
- Source/Examples/DataGrid/DataGridDemo/Examples/WrapItems/MultitypeMatrixExample.xaml.cs
- Source/PropertyTools.Wpf/DataGrid/DataGrid.cs
> Enable collection synchronization

- CHANGELOG.md
- Source/Examples/PropertyGrid/ExampleLibrary/Examples/EnumsExample.cs
- Source/PropertyTools.Wpf/Controls/RadioButtonList/RadioButtonList.cs
- Source/PropertyTools.Wpf/Converters/EnumToBooleanConverter.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGridControlFactory.cs
> PropertyGrid: add support for nullable enums

- CHANGELOG.md
- Source/Examples/PropertyGrid/ExampleLibrary/Examples/EnumsExample.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGridControlFactory.cs
> Support BrowsableAttribute on enum items when shown as ComboBox or ListBox

- Source/PropertyTools.Wpf/DataGrid/DataGrid.cs
> Refresh collection view in DataGrid #135

- CHANGELOG.md
- Source/Examples/DataGrid/DataGridDemo/DataGridDemo.csproj
- Source/Examples/DataGrid/DataGridDemo/Examples/ExceptionExample.xaml
- Source/Examples/DataGrid/DataGridDemo/Examples/ExceptionExample.xaml.cs
- Source/PropertyTools.Wpf/DataGrid/Operators/DataGridOperator.cs
> handle exception when pressing Delete

- CHANGELOG.md
- Source/Examples/DataGrid/DataGridDemo/DataGridDemo.csproj
- Source/Examples/DataGrid/DataGridDemo/Examples/NullableExample.xaml.cs
- Source/Examples/DataGrid/DataGridDemo/Examples/VectorExample.xaml
- Source/Examples/DataGrid/DataGridDemo/Examples/VectorExample.xaml.cs
- Source/PropertyTools.Wpf/DataGrid/DataGrid.cs
- appveyor.yml
> Fix clear enum values in DataGrid

- CHANGELOG.md
- CONTRIBUTORS
- Source/Examples/DataGrid/DataGridDemo/DataGridDemo.csproj
- Source/Examples/DataGrid/DataGridDemo/Examples/ScrollViewerExample.xaml
- Source/Examples/DataGrid/DataGridDemo/Examples/ScrollViewerExample.xaml.cs
> Changelog and Example

- CHANGELOG.md
- Source/Examples/DataGrid/DataGridDemo/DataGridDemo.csproj
- Source/Examples/DataGrid/DataGridDemo/Examples/DisabledExample.xaml
- Source/Examples/DataGrid/DataGridDemo/Examples/DisabledExample.xaml.cs
- Source/Examples/DataGrid/DataGridDemo/Examples/EasyInsertExample.xaml
- Source/PropertyTools.Wpf/DataGrid/DataGrid.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGridControlFactory.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGridOperator.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyItem.cs
- Source/PropertyTools/DataAnnotations/EasyInsertAttribute.cs
> Datagrid fixes

- README.md
looks better (imo) and much easier to use on phones.
> Replace project links with shields

- CHANGELOG.md
- Source/PropertyTools.Wpf/DataGrid/DataGrid.cs
- Source/PropertyTools.Wpf/DataGrid/IDataGridOperator.cs
- Source/PropertyTools.Wpf/DataGrid/Operators/DataGridOperator.cs
- Source/PropertyTools.Wpf/DataGrid/Operators/ListListOperator.cs
- Source/PropertyTools.Wpf/DataGrid/Operators/ListOperator.cs
- Source/PropertyTools.Wpf/DataGrid/Operators/WrapItemsOperator.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGridControlFactory.cs
> Improve DataGrid

- CHANGELOG.md
- Source/Examples/DataGrid/DataGridDemo/Examples/CustomTypeDescriptorExample.xaml
- Source/Examples/DataGrid/DataGridDemo/Examples/CustomTypeDescriptorExample.xaml.cs
- Source/PropertyTools.Wpf/DataGrid/DataGrid.cs
- Source/PropertyTools.Wpf/DataGrid/IDataGridOperator.cs
- Source/PropertyTools.Wpf/DataGrid/Operators/DataGridOperator.cs
- appveyor.yml
> Support custom type descriptors

- CHANGELOG.md
- Source/PropertyTools.Wpf/TreeListBox/TreeListBox.cs
- appveyor.yml
> Apply workaround for height-must-be-non-negative exception 

- Source/PropertyTools.Wpf/DataGrid/DataGrid.cs
https://github.com/PropertyTools/PropertyTools/issues/217
> DataGrid returning incorrect 'SelectedItems' when sorted #217

- CHANGELOG.md
- Source/Examples/Controls/ControlDemos/ControlDemos.csproj
- Source/Examples/Controls/ControlDemos/Examples.xml
- Source/Examples/Controls/ControlDemos/Pages/CheckMarkPage.xaml
- Source/Examples/Controls/ControlDemos/Pages/CheckMarkPage.xaml.cs
- Source/Examples/Controls/ControlDemos/Pages/ColorPickerPage.xaml
- Source/Examples/DataGrid/DataGridDemo/DataGridDemo.csproj
- Source/Examples/DataGrid/DataGridDemo/app.config
- Source/Examples/ItemsBag/ItemsBagDemo/ItemsBagDemo.csproj
- Source/Examples/PropertyGrid/CustomFactoryDemo/CustomFactoryDemo.csproj
- Source/Examples/PropertyGrid/PropertyGridDemo/Examples/AdvancedTypesExample.cs
- Source/Examples/PropertyGrid/PropertyGridDemo/PropertyGridDemo.csproj
- Source/Examples/PropertyGrid/SimpleDemo/SimpleDemo.csproj
- Source/Examples/PropertyGrid/UndoRedoDemo/UndoRedoDemo.csproj
- Source/Examples/TreeListBox/AddRemoveDemo/AddRemoveDemo.csproj
- Source/Examples/TreeListBox/DirectoryDemo/DirectoryDemo.csproj
- Source/Examples/TreeListBox/TreeListBoxDemo/TreeListBoxDemo.csproj
- Source/PropertyTools.Wpf.ExtendedToolkit/PropertyTools.Wpf.Extended.Toolkit.csproj
- Source/PropertyTools.Wpf.Tests/Helpers/ReflectionMathTests.cs
- Source/PropertyTools.Wpf.Tests/PropertyTools.Wpf.Tests.csproj
- Source/PropertyTools.Wpf/Chrome/ButtonChrome.cs
- Source/PropertyTools.Wpf/Chrome/SystemDropShadowChrome.cs
- Source/PropertyTools.Wpf/Controls/CheckMark/Generic.xaml
- Source/PropertyTools.Wpf/Controls/ColorPicker/Generic.xaml
- Source/PropertyTools.Wpf/Controls/PopupBox/Generic.xaml
- Source/PropertyTools.Wpf/Controls/SpinControl/Generic.xaml
- Source/PropertyTools.Wpf/PropertyTools.Wpf.csproj
- appveyor.yml
> Add support for .NET Core 3.0

- CHANGELOG.md
- Source/Examples/DataGrid/DataGridDemo/Examples/AutoWidthExample.xaml
- Source/PropertyTools.Wpf.ExtendedToolkit/PropertyTools.Wpf.Extended.Toolkit.csproj
- Source/PropertyTools.Wpf/DataGrid/DataGrid.cs
- Source/PropertyTools.Wpf/PropertyTools.Wpf.csproj
- Source/PropertyTools/PropertyTools.csproj
> Fix auto width issue

- Source/Examples/PropertyGrid/PropertyGridDemo/App.xaml
- Source/Examples/PropertyGrid/PropertyGridDemo/Converters/MultiValueToStringConverter.cs
- Source/Examples/PropertyGrid/PropertyGridDemo/CustomControlFactory.cs
- Source/Examples/PropertyGrid/PropertyGridDemo/Examples/NotifyDataErrorInfoSeverityExample.cs
- Source/PropertyTools.Wpf/PropertyGrid/IPropertyGridControlFactory.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyControlFactoryOptions.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGrid.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGridControlFactory.cs
> Tooltip is not updated immediately when a property receives Warning after Error

- Source/Examples/PropertyGrid/PropertyGridDemo/CustomControlFactory.cs
- Source/Examples/PropertyGrid/PropertyGridDemo/Examples/NotifyDataErrorInfoSeverityExample.cs
- Source/PropertyTools.Wpf/PropertyGrid/IPropertyGridControlFactory.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGrid.cs
- Source/PropertyTools.Wpf/PropertyGrid/PropertyGridControlFactory.cs
tab header colors are not consistent with warning and erros.
> #255 tabs are not consistent
